### ISSUE TITLE
Bio.jl version and ragel/colm versions

### ISSUE THREAD

**Issue by yesimon** [BioJulia/Bio.jl#137]
I'm using julia 0.4, Bio.jl from master and ragel release 7.0.0.6 and colm 0.13.0.3, but ragel is not working properly. It outputs a large number of deprecation syntax warnings `WARNING: deprecated syntax "{a,b, ...}"`, as well as `ERROR: LoadError: LoadError: LoadError: LoadError: syntax: inconsistent shape in cell expression` when trying to parse a bed file after using ragel to compile the bed parser. 

What are the proper versions of software I should be using for parser generation to work?

**Comment by bicycle1885** [comment]
The current developmental release emits invalid Julia code. I've send some pull requests to the repository (https://github.com/colmnet/ragel), but it still has some bugs. I couldn't fix them since I don't know the Colm language very well. So, I'm going to file issues there. At the moment, I'm using our fork of Ragel at https://github.com/BioJulia/ragel7. It works fine, and its dependency is written in README (https://github.com/BioJulia/ragel7/blob/master/README).

**Comment by Ward9250** [comment]
@yesimon Does it now work for you with BioJulia/ragel7?

**Comment by yesimon** [comment]
The Biojulia/ragel7 repository works. I haven't tried master colmnet/ragel with @bicycle1885's latest merged commits. I was working on a GFF3 parser branch but looks like it's already covered in #183 :laughing:. I'll just PR the attributes parser. I was getting some weird results with a header state for header lines `#` and not executing the last `%` action.

**Comment by Ward9250** [comment]
The BioJulia project no longer uses Ragel for code generation, and parsers that currently use ragel generated code will be replaced in the near future. This issue can be closed.

**Comment by bicycle1885** [comment]
Ragel is/will be replaced with [Automa.jl](https://github.com/BioJulia/Automa.jl).
