### ISSUE TITLE
Entrez utilities

### ISSUE THREAD

**Issue by abhijithch** [BioJulia/Bio.jl#149]
Would this be the right package to have the Entrez utilities features? I would like to ask the repository owners if there are any plans for developing these features, and if I could contribute? Could someone please tag this with `Question` label.

**Comment by Ward9250** [comment]
Hi @abhijithch! I think this is absolutely the right package for the Entrez utilities. We have given some thought to adding a module to the package for database queries (see #52 ), and we're always happy for others to make contributions to BioJulia repos: we recently started getting automated docs and web presence online, with [contributing help](biojulia.github.io/Contributing/latest).

**Comment by bicycle1885** [comment]
Yes, I'm going to implement utilities for accessing DBs like Entrez (#52) but now I'm focusing on algorithms and data structures before that. Feature requests and contributions are welcome, of course.

**Comment by abhijithch** [comment]
Thanks @Ward9250 and @bicycle1885, I will post a rough script of my needs. It will be great to have your feedback before I can fine tune it.

**Comment by abhijithch** [comment]
```
using Requests
import Requests: get, options
using LightXML

function fetch_pubids(db, terms)
    src="http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    resp=get(src; query = Dict("db"=>db, "term"=>terms))

    doc=LightXML.parse_string(bytestring(resp.data))
    root_elem=LightXML.root(doc)
    idList_elem=LightXML.get_elements_by_tagname(root_elem, "IdList")
    ids_xml=LightXML.get_elements_by_tagname(idList_elem[1], "Id")

    ids = Int[]
    for i=1:length(ids_xml)
        push!(ids, parse(Int, LightXML.content(ids_xml[i])))
    end
    return ids
end
```

The above very basic script returns the PUB IDs of the articles in which `terms` occur.  This currently works only for one term, but I can handle multiple terms by appending something like `cancer AND diabetes`. Couple of other things to be taken care of are, having options to select the type of fields to search the terms from, like `Abstracts`, `pdat`, `All fields` etc. 

So an ideal pseudo function for fetching the PUBMED ids for specific terms would be,
```
function search(db, terms, return_type; kwargs...)
    src = "http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    query = Dict("db"=>db, "term"=>terms, kwargs)
    resp = get(src; query)
    return filter_resp(resp, return_type)
end
```
, where `kwargs` will have arguments like, `retmax` and the `return_type` will specify what fields to return like `pubid`. Does this seem ti be a right approach, @Ward9250 and @bicycle1885?

**Comment by bicycle1885** [comment]
I think a more extensible approach is placing a general core of the interface to Entrez and thin wrappers around it. For example, create a type that keeps all information about query and its result:
```julia
immutable EntrezSearchResult
    uri::URI  # query URI
    timestamp::DateTime  # access date and time
    success::Bool  # the query finished successfully or not
    doc  # the result XML object
end
```
, then write accessors to the content:
```julia
function pubids(r::EntrezSearchResult)
    # parse `d.doc` and return IDs
end

function nhits(r::EntrezSearchResult)
   # parse `d.doc` and return the number of records.
end
```

In this case, the `search` function would look like:
```julia
function search(db, terms; kwargs...)
    src = "http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    query = Dict("db"=>db, "term"=>terms, kwargs)
    resp = get(src; query)
    return EntrezSearchResult(get(resp.request).uri, now(), resp.status == 200, LightXML.parse_string(bytestring(resp.data)))
end
```
though the name `search` seems too broad for the Entrez-specific function.

**Comment by abhijithch** [comment]
Yes, you are right, I was going to talk about the types next. We could use `esearch`, that is what is used in biopython.

**Comment by Ward9250** [comment]
Is search a method that exists already for other types in the biojulia universe? If so, then keeping the name search might make more sense. Especially if different db is some database type that search would be dispatched on. I presume esearch means enter search. With julia's system, it makes more sense you just call the method search, on a an entrez db type.

**Comment by bicycle1885** [comment]
@Ward9250 Do you mean defining database types like `EntrezDB` and `Base.search` like `Base.search(::Type{EntrezDB}, db, terms; kwargs...)`?

**Comment by abhijithch** [comment]
There seems to be a `search` in BioJulia/IndexableBitVectors.jl.

**Comment by bicycle1885** [comment]
Yes, but it has totally different semantic from database search. It may be better to define our own search function like `dbsearch` for database search.

**Comment by Ward9250** [comment]
@bicycle1885 Yes or something similar if that sounds reasonable: using multiple dispatch to make the process of querying all kinds of dbs very general. But mainly I think using search rather than something like search is more general, and makes more sense to a high level biology user "I want to search this db, I wonder what that function is called?", calling it `esearch` seems like a small unnecessary curveball.

**Comment by bicycle1885** [comment]
I agree that the name, `esearch`, is hard to figure out what it does and to find out it for users. I'm not completely sure, but recently I'm thinking that each function should have only one meaning in Julia. The `Base.search` function is defined as a function searching a query/pattern in another string. If we extend the function for database search, it has at least two different meanings that should be documented. Defining polysemous verbs may be an abuse of multiple dispatching in Julia.

**Comment by abhijithch** [comment]
`dbsearch` sounds apt.

**Comment by Ward9250** [comment]
I don't think two versions of a function having two meanings is a problem since there's examples in the base module, the * and ^ operators mean something completely different for strings and numbers, and I don't think this generates unnecessary confusion or abuses the system.

I think the difference in meanings for ^ and * for numbers and strings is much more of an extreme difference in semantics: multiplication vs concatenation. Whereas for Base.search and databases we're talking about: Searching a string for a query, vs searching a database for a query. I think this is a small semantic difference cf the semantic difference that exists in the * and ^ methods.

**Comment by Ward9250** [comment]
An alternative for consideration, the "find" method. `Base.find`, is used to find an element in an array or collection of elements which matches some value or query. I.e. Here is a collection of things (an array, or in our case perhaps a db?), and we want to find the things in this collection that meet some value (in the case of a db, our query).

**Comment by Ward9250** [comment]
I'm happy for the method to be called dbsearch, because it does make sense. But I think in general where possible we should have a policy of trying to extend existing methods where it makes sense and is reasonable, because a massive load of different function names that are unique to different packages is also not great, as you've got to remember them or keep looking at the docs. And there is a reasonable argument to use Base.search in that it's a very obvious name and makes some semantic sense, even if the semantics for searching strings and databases are different.

**Comment by bicycle1885** [comment]
I think the meaning of the `*` operator in Julia is the binary operator of a [monoid](https://en.wikipedia.org/wiki/Monoid), which has associativity and a unique identity element, and `^` can be regarded as a repetitive application of `*`. In this point of view, these operators have a single meaning, even though these are applicable to both numbers and strings.

> we should have a policy of trying to extend existing methods where it makes sense and is reasonable,

We will need to make a consensus on "make sense" and "reasonable" to extend existing methods. Let's use the name `dbsearch` for now since its meaning is apparent from the name. If we reach a consensus that this function is just a natural extension of `Base.search`, then we can replace it as such.

**Comment by Ward9250** [comment]
Agreed. The possibility exists, since it may also be argued that databases is too far from arrays and strings for search and find, that we use methods that are verbs unique to database searching, but consistent across different databases.

**Comment by kescobo** [comment]
I haven't looked, but there are probably packages for navigating other databases (MySQL etc) - seems like we could take a cue from them. I've worked a bit with MongoDB, and they use the operators `find` or `find_one` for example. Not sure if there's a convention, but it might be worth considering.

**Comment by abhijithch** [comment]
Extending the functionality what has been discussed for `dbsearch`, if we are to have Term Document Matrix, can we consider the PUBMED ids to index the documents? Is there a way to find out the total number of articles in PUBMED?

**Comment by INSARKAR** [comment]
Our team has been working on implementing this as well as other common NLM resources (e.g., UMLS): https://github.com/bcbi/NLM.jl
