### ISSUE TITLE
Visually enhanced notations

### ISSUE THREAD

**Issue by diegozea** [BioJulia/Bio.jl#19]
Maybe, in the future, we can add support for [other visuallizations, different from ascii based IUPAC](http://en.wikipedia.org/wiki/Nucleic_acid_notation)

**Comment by Acrylami** [comment]
I am attempting to work on this- just trying to figure out how to work with this big project :)

**Comment by kescobo** [comment]
@Acrylami - That's great! But I think you want to work on this over on [Biosequences](https://github.com/BioJulia/BioSequences.jl), since the functionality for working with these sorts of sequences has been migrated to that package (see #425 for a long discussion about the split)

Feel free to open up an issue/PR over there, and don't hesitate to ask there or on gitter if you run into issues :-)
