### ISSUE TITLE
Changing bit-level encodings of nucleotides.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#244]
As I and @Ward9250 briefly discussed in Gitter, we're considering changing bit-level encodings of nucleotide types (i.e. `DNANucleotide` and `RNANucleotide`). In short, the new encoding scheme I propose is a kind of [one-hot](https://en.wikipedia.org/wiki/One-hot) encoding: A = 0b0001, C = 0b0010, G = 0b0100, and T/U = 0b1000. This keeps the order A < C < G < T. Ambiguous nucleotides are encoded using bit-wise OR of these nucleotides; especially, gap = 0b0000 and N = 0b1111.

Upsides:
1. Simple - one can easily understand this encoding and infer what ambiguous nucleotides will be (e.g. adenine OR thymine = 0b1001).
2. Faster compatibility check - Current compatibility check (`iscompatible`) relies on a lookup table; this will be a single bit-wise OR operation, which will be faster.

Downsides:
1. Change of nucleotide ordering - `"ACGTMR...N-"` will become `"-ACMG...N"` and unambiguous nucleotides will be interleaved among all nucleotides.
2. Anything else?

Any thoughts?

**Comment by Ward9250** [comment]
So I'd like to consider/discuss taking on some ideas from the bit encoding from ape. Mostly because it has features which I think might benefit the distance computations I'm trying to code. I wonder if the use of an additional bit to represent gaps, would allow me to improve functions like this:

```julia
"""
    unambiguous_diff{T<:Nucleotide}(a::T, b::T)

Test if two nucleotides can be unambiguously determined to be mutated or non-mutated.

# Examples

```julia
is_ambiguous_leinient(DNA_A, DNA_A)
is_ambiguous_leinient(RNA_A, RNA_A)
is_ambiguous_leinient(DNA_A, DNA_R)
is_ambiguous_leinient(DNA_A, DNA_T)
is_ambiguous_leinient(DNA_R, DNA_R)
is_ambiguous_leinient(DNA_R, DNA_Y)
is_ambiguous_leinient(RNA_R, RNA_Y)
```
"""
@inline function is_ambiguous_leinient{T<:Nucleotide}(a::T, b::T, model::Union{N, Raw, JC69})
    return (a > DNA_T || b > DNA_T) && a == DNA_Gap || b == DNA_Gap || iscompatible(a, b)
end
``` 

Briefly, if either of two nucleotides are ambig codes, AND is one is a gap or the two are compatible, THEN return true as it is not possible to conclude whether two bases are different or not. The function involves 5 logical operations. IF some of these can be checked at the same time, by combining them into a few bitwise operations as a result of the encoding, I'd be very happy as this kind of function is called for every site in two sequences, so it needs to be quick and concise. 

Extra bits for ambiguity and gaps may also help preserve the order. But operations that depend on order could be rewritten otherwise: for example `isambiguous` current checks if nucleotide > DNA_T (IIRC), but this could be recoded just to check that the UInt8 is a power of 2, if it is, one bit is set, so it is not ambiguous.

**Comment by timbitz** [comment]
I really like the idea of the one-hot encoding for 4-bit, it makes a lot of intuitive sense, and makes bitwise operations really straight forward I think.  From an alternative standpoint of consistency, I can also see how it makes sense to have 0b0000 through 0b0011 be equivalent ACGT nucleotides in all encodings.

I am also curious about how it will affect conversion or comparison of sequences between 4-bit and 2-bit encodings.  Is there unnecessary overhead here?  My main concern would be in terms of the current set-up of FASTQParser -> 4-bit encoding, to then frequent conversion for the purposes of mapping seeds or k-mers using 2-bit encoding, although this could be solved by some handling of N's (which I still think are superfluous given the qual string) and 2-bit encoding for FASTQ as I think @bicycle1885 mentioned previously?

**Comment by bicycle1885** [comment]
I think the change of ordering is a minor problem but losing the intuitive mapping between {0, 1, 2, 3} and {A, C, G, T} may be a little bit cumbersome. 

Conversion from 2-bit to 4-bit encoding would be cheap since it can be done by a bit-shift operation and no validity check is needed. Anyway, I will need to try the new encoding and then add 2-bit encoding for FASTQ.

**Comment by kdmurray91** [comment]
:+1:  to the one-hot proposal. From memory, this exactly is what NCBI's `4na` format uses amongst others.

**Comment by bicycle1885** [comment]
One-hot encoding is also used in BAM, which means reading sequences from BAM will be much faster since conversion from a BAM sequence to DNASequence can be removed completely.

**Comment by bicycle1885** [comment]
In my local benchmarks, sequence searches became slightly faster.
![benchmarks](https://cloud.githubusercontent.com/assets/905683/17618113/dcc299b6-60b8-11e6-9795-6242a65d318b.png)

**Comment by kdmurray91** [comment]
Awesome!

**Comment by Ward9250** [comment]
What do you think is the cause of the difference in translate_rna?

**Comment by bicycle1885** [comment]
I have no idea, but it may be due to `Bio.Seq.find_next_ambiguous` because I cannot write it in a bit-parallel manner.

**Comment by bicycle1885** [comment]
The performance regression of `translate_rna` is almost removed. Please see the latest figure: https://github.com/BioJulia/Bio.jl/pull/259#issuecomment-240006780.

**Comment by bicycle1885** [comment]
I'd like to merge #259 and close this issue if no objections to this change.

**Comment by Ward9250** [comment]
:+1: :)
