### ISSUE TITLE
Offboarding & Onboarding

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#271]
So following gitter discussion this is to discuss the issue off offboarding and onboarding of team members.

Comments sparking discussion from Gitter copied in:

**Comment by Ward9250** [comment]
@blahah:

@bicycle1885 @Ward9250 @kdmurray91 hey, I'd like to apologise for not having contributed, really at all, to biojulia this year. I promised to put some time into community + docs stuff and then failed to meet that commitment. I was looking over the github orgs I'm in, and it strikes me that there are a number of inactive people on the biojulia team
I propose that I and any other team members who don't contribute frequently be removed from the team, and that a community process of team onboarding be activated so that the people who are doing the work get to have a say in the working of the organisation
of course we can all still hang out here, contribute by the normal channels etc., but it just seems like a privilege aggregator to keep historically active people around, as well as a security risk

**Comment by Ward9250** [comment]
@Ward9250:

I'm rather worried about @dcjones, he just stopped being active across quite a lot of projects. (I was less worried about @blahah as we're connected through more channels )

**Comment by Ward9250** [comment]
@blahah:

I have some info about Daniel that I can share privately, but I am also concerned and would love to hear from/about him

**Comment by Ward9250** [comment]
@Ward9250:

Sounds like a reasonable idea, but we'd need to have an open and formal process for both onboarding and let's call it offboarding.
In the interest of credit where credits due, we should keep a list of contributors so even though some members may leave, they will be remembered.

**Comment by Ward9250** [comment]
@blahah:

for anyone concerned about me, which I hope is nobody, I have had a rollercoaster year of Mozilla fellowship exploding my time commitments by an order of magnitude, new baby, medical issues for myself and partner, quitting my horrible PhD about 3 months before submission, and finally leaving my native land of the UK to relocate my family and business to Kenya
I have so many pressures on my time, all of them my own fault for being so optimistic about what I could be involved in, that I have unfortunately let many relationships and commitments drop. I'm truly sorry to have not put more time into Biojulia this year. I care about it more than many of the other projects and communities I'm involved in, but the simple fact is that Biojulia folks don't push/pressure me so hard as some of the others.
@Ward9250 offboarding is awesome
I agree about a history of committers - I just don't want to be the ominous team member who never speaks and was there from the beginning, so wields some psychological and social power
I'd rather it was clear that I was involved at the start, then left and now have no more say than any other contributor (and less than many)
my concern is based on seeing so many other great communities struggle
with personality cults

**Comment by Ward9250** [comment]
@Ward9250:

So one of the first steps I think it to agree on process. We can discuss here or in an issue. Then we can add appropriate sections about the processes on the Contributing documentation site.

**Comment by Ward9250** [comment]
I propose the following procedure for offboarding at the top of my head:

First, we should define inactive: I'd suggest any activity on Gitter or commenting also counts, as sometimes people are active in the community but don't have time for lots of code writing, and productivity comes in spurts

Then we should define the offboarding process, I imagine it roughly like this:

First create two new issue labels: Offboarding notice, and inactivity notice.

1. If a member is inactive for many months (we can decide how many) an admin member can open an issue, @ mentioning the person in question so they will be notified.
The issue should state concern at their inactivity, and that in accordance with the agreed BioJulia protocol for offboarding, this offboarding notice will be displayed for a period of time (we can decide period length).
If the individual responds to the notice with an explanation of the inactivity and how long it will last, then no further action need be taken.

2. Admin members might not do this immediately if prior notification of inactivity, reduced activity (although reduced activity should not count as inactive and so on its own would not lead to offboarding) or periods of busy-ness is given. But the notice should say for how long the inactivity will last. We can create an issue label for such notices so they are not lost in Gitter.

3. The notices or explanation of inactivity mentioned in 1 and 2 need not be detailed in the interest of individual privacy, it can be as brief as "high workload" or "personal factors".

4. If the individual member does not respond to the offboarding notice within the time period, then the administrators may remove the member from any groups of the organisation that give them unwarranted permissions that constitute some security risk given the lack of activity.

5. The **most important point**: It is to be understood in every case, offboarding does not represent a rejection of the member from the group, and that offboarding is completely reversible, a user may join, contribute, become inactive for a long period of time, before getting more time and joining their old groups again - they are always welcome.

**Comment by bicycle1885** [comment]
The overall offboarding looks good to me.

One thing I'm concerning is `@` mentioning may not be enough to notice the person; the person may not have access to GitHub for a technical reason at the moment. So I suggest notification via e-mail as well as `@` mentioning on GitHub.

**Comment by Ward9250** [comment]
That sounds good to me!

**Comment by Ward9250** [comment]
We should decide how long a period of inactivity should be before such an offboarding issue is posted. 3 months? 4 months? And we should define inactivity, as a starting point I propose:

"We define inactivity is defined as a lack of commits and comments on PR's, a lack of activity on Gitter or other any such BioJulia forums, without any prior notification, for X months. Reduced activity during a period of X months does not constitute inactivity." 

An additional idea - we could have an alumnus group with stripped down permissions that offboarded people are moved to?

**Comment by kescobo** [comment]
This looks good - I think Point 5 is really critical. 

Do people in the org have formal roles that aren't recorded in git activity? In other words, if someone is "officially" doing outreach, or managing money etc. Beyond recording that, it seems that git logs people's contributions, so it may not be necessary to stress out over getting a full accounting. 

@bicycle1885 Are the e-mail addresses of everyone in the leadership known? It seems somewhat implausible that someone would have access to e-mail but not github (and @ mentions are sent to e-mail anyway). Besides, if someone is removed because they missed the notification, they can always be reinstated when that becomes clear (and perhaps there should be a notice to that effect in the issue once the removal is to be put into effect).

**Comment by Ward9250** [comment]
@kescobo Because we don't have much other than code development going on up until now, git, and activity on github, and gitter largely judges people's activity i.e. We all noticed, for example the absence of Dan. BUT as I speculated previously, as some more of the kind of acitivties you mentioned will be carried out as I push them in my postdoc, and in general as the project becomes larger. Multiple groups with more specific roles and therefore slightly differing methodologies of determining inactivity may manifest. In any such case, the definition of inactivity should be defined at the creation of the role, and our official policy in our docs/website, updated.

I believe the email addresses of everyone in leadership is known, certainly my and other people's profiles have at least one channel through which to contact them. I think the fact offboarding is reversible, and that they can always be re-instated is important and is covered by point 5, so in every issue, point five should probably be copied and pasted in.

**Comment by blahah** [comment]
@kescobo personally I have all github email notifications turned off - I already get more emails than I can read :). If I'm inactive on github it means I won't be getting notifications and I am probably not alone - therefore I think having an email in addition to an @ mention would cover all bases.

I agree about git logs containing the information about code contributions, but there are more ways to contribute than just code - for example providing help on gitter, or contributing ideas and support. So I think recognising the efforts of all contributors, in some more explicit way than the git logs, would be a nice way to build community rapport.

**Comment by kdmurray91** [comment]
Hi All,

Offboarding sounds like a great idea (Ironically, I'm catching up on the conversation now, after a few days away from computers at the beach!).

I'd like to second @Ward9250's idea of an "ex-members" group, I think that could be used as a way of showing past membership of a community, a history that may not be reflected in `git log`.

And another 2nd to @blahah's points about email notification: I just binned the ~300 emails from github after 4 days away.

Cheers,
K

**Comment by Ward9250** [comment]
@blahah Indeed contributions are not just code, which is why it's important gitter and commenting and reviewing are also in the definition of inactivity proposed.

**Comment by kescobo** [comment]
I 100% agree that tracking folks' contributions other than code is essential. Apologies if I implied otherwise. And if there's some location for e-mail addresses, an extra notification seems sensible (perhaps it would be worth including the need to get a permanent e-mail address in the **on**boarding procedure for future org positions).

The thing I was trying to address is information redundancy. The more places that knowledge about contributions are kept, the more opportunities there are for information sources to diverge. So if most of the contributions to this point are code, and that knowledge is stored in git history, I think you should think really hard about duplicating that information. Perhaps, to address @blahah 's point about explicitness - maybe there's a simple way to plug in to the github API to surface that information?

For stuff that's not captured in git history, or not easily surfaced, I definitely agree that it's worth the effort to maintain a record.

**Comment by Ward9250** [comment]
> So if most of the contributions to this point are code, and that knowledge is stored in git history, I think you should think really hard about duplicating that information.

@kescobo I'm confuzzled at this point, I'm not sure duplicating any info from the git history was suggested?

**Comment by kescobo** [comment]
@Ward9250 Sorry for being opaque - my brain is in like 100 places right now. 

As a hypothetical - imagine a future where there are 10 people that are contributing to a great deal of code development. There's an org document somewhere that lists `Principle Developers` or something. 

At some point, dev4's contributions start to fall because he's got another project taking his time. Some new dev11 starts contributing a huge amount, gets permissions to merge pull requests etc, She starts to be considered integral to development, but she's not listed in `Principle Developers`. Meanwhile, even though everyone agrees that dev4 is no longer taking a central role, he's still listed in `Principle Developers`. 

This is a trivial example of course, and maybe it's not that big a deal to update the document, but having recently joined a large organization where there are lots of moving parts, it's super easy for the ball to be dropped on something like this, since it's not clear whose responsibility lies where. 

Perhaps that's what these onboarding and offboarding procedures will cover, and I'm fretting over nothing. But to the extent it's possible and practical, I think automatic recording is preferable to manual, and if it's manual the procedures should be explicitly linked to reporting.

**Comment by Ward9250** [comment]
@kescobo I would argue that in case of documents documenting developers, unless it's for the website or something it's not needed (unless we start to record emails in a document, but most github profiles have emails, and we can specify in onboarding, members profiles have to have at least one active email address, which solves that too), as the organisation teams are in and of themselves that document.

**Comment by Ward9250** [comment]
Making a living issue, like the other community issue.

**Comment by BenJWard** [comment]
This guidance has been written solidly into the Contributing guide. Since Bio.jl is legacy, this being a living issue has lost its point. Closing.
