### ISSUE TITLE
Distributed and Threaded Parallelism in the BioJulia Suite

### ISSUE THREAD

**Issue by ChrisRackauckas** [BioJulia/Bio.jl#347]
Hey, I'm a mathematical/systems biologist whose been mostly on the sidelines of BioJulia for a bit but am thinking about helping with parallelism. I am looking for the current implementations and am not finding any. Could someone give me the lowdown of the current state of parallelism in BioJulia and what areas should be targeted in the nearest of future?

Another question is, what would be the the right architecture for this? Should the distributed parallel algorithms be separate packages or integrated directly into the main packages? I'd likely be making good use of [ParallelDataTransfer.jl](https://github.com/ChrisRackauckas/ParallelDataTransfer.jl) so this would add a (lightweight and pure-Julia) dependency.

Let know some good ways to start helping BioJulia with parallelism!

**Comment by Ward9250** [comment]
As far as I'm aware, most of the code, if not all of it that has been implemented in Bio.jl is single threaded, although I believe maybe multithreading is used in some of the sequence alignment code.

I'm currently working on 'parallelism' in code I'm writing but it's still single threaded i.e. bit parallel operations and simd use. Most computations involving types representing single sequences or single individuals or single samples benefit from having such single threaded operations implicitly parallelized using those two techniques - plus good algorithm choice, but in biology since operations need to be repeated on multiple sequences or individuals or samples, that's where multi-process or multi-threaded parallelism is more easily applied and to greater effect.

So one starting point could be defining operations like reverse complement, reverse, translate and so on - operations currently implemented for a single BioSequence variable, for Vectors of BioSequences.

The work I'm doing on population genetics and variant data will eventually probably use multithreaded and multiprocess parallelism in a similar way to do operations on multiple individuals at once, but right now I'm working on getting the algorithms chosen written in julia to be very bitparallel and vectorised. 

As for whether parallel features in a seperate package... depends I guess, that's probably context dependent, but since parallel code just runs in serial on a single process anyway and is just using base julia I would have no objection to parallel code being in Bio.jl in general. 

Jump in guys, what do you think about this question?

**Comment by vchuravy** [comment]
We are also currently planning a rework of the parallel infrastructure in Base so if you are interested in something specific or if you are running into limitation of the currently implementation please let us know.

**Comment by ChrisRackauckas** [comment]
Is there an issue explaining the planned rework of Base?

**Comment by vchuravy** [comment]
@ChrisRackauckas No not yet. I will ping you once we have one.

**Comment by bicycle1885** [comment]
The only use of multi-thread parallel processing in BioJulia is in [BGZFStreams.jl](https://github.com/BioJulia/BGZFStreams.jl), where we can parallelize inflation processing. I think this is the same idea of [sambamba](http://bioinformatics.oxfordjournals.org/content/early/2015/02/18/bioinformatics.btv098) because inflation is the main bottleneck when handling BAM files.

I'm not sure the best architecture for parallelism but I think it should be isolated from this package so that the user can select the best infrastructure/package for parallel processing. To do that, we should keep this package thread-safe wherever possible.

**Comment by Ward9250** [comment]
@vchuravy Thanks for the heads up :)
