### ISSUE TITLE
Any interest in statistical genetics from BioJulia community?

### ISSUE THREAD

**Issue by klkeys** [BioJulia/Bio.jl#400]
I have loosely followed the development of Bio.jl. So far I do not see great interest in statistical genetics. Is this by design or perhaps for lack of contributors? 

To illustrate with a concrete case, I developed [PLINK.jl](https://github.com/klkeys/PLINK.jl) as a hack to deal with [PLINK](https://www.cog-genomics.org/plink2/) [BED files](https://www.cog-genomics.org/plink2/formats#bed) (different from UCSC BED files). Though many people are shifting to whole genome analysis and VCF, there are still many datasets encoded in BED format. I would be happy to continue development of PLINK.jl or some derivative of it within the BioJulia umbrella, assuming that the community deems it useful.

Some statgen people have begun to adopt Julia (e.g. [OpenMendel](https://github.com/OpenMendel)) but the uptake is still slow.

Note: if maintainers prefer, I can move this conversation to Gitter.

**Comment by bicycle1885** [comment]
> Is this by design or perhaps for lack of contributors?

Lack of contributors 😢 . I think it is great to have statistical genetics tools in BioJulia but I have almost no knowledge about what kinds of tools are needed in the community.

I know PLINK is a widely used software in statistical genetics. Supporting some formats used in it sounds a good idea to me. So, I'd like to know which file formats are the most commonly used in the community. VCF and BCF will be merged soon (#378). Is PLINK BED common, too? Are there any other file formats you often use in your work?

**Comment by jgreener64** [comment]
Not my area of expertise but if you wanted to develop this stuff as part of BioJulia @klkeys that would be cool :+1:

**Comment by Ward9250** [comment]
It has been, so far, due to lack of contributors. However, I am aware statistical genetics people are starting to look at julia - I am named on the grant that MIT and UCLA researchers have submitted to extend OpenMendel, and they were going to base it off of the work I'm currently doing on my postdoc; trying to improve on how we store and represent SNP like data that is typically stored in a SnpArrays - like matrix format (including VCF and PLINK), since we use those kinds of allelic data all the time in population genetics. I planned on some of the core functionality of OpenMendel to be moved to Bio.jl when such datatypes are ready.
