### ISSUE TITLE
Move organisation level issues

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#434]
I think we should move organisation and community level issues to BioJulia/Community-Issues, to make engaging in the community and communicating with maintainers and admins clearer for all members, especially now Bio.jl is in the process of becoming a meta-package - we need a new hub repo for discussing community issues.

**Comment by kescobo** [comment]
This kinda makes sense, though I worry a bit about over-fragmentation. I'm not sure that having a repo specifically for community-level discussion increases clarity. I don't think it would be obvious to new users to look for that repo, so we'd have to point people somewhere anyway.

Seems like BioCore.jl could become the new spot for community-related issues instead. Alternatively, the repo for the website (BioJulia.github.io) might make sense.

**Comment by jgreener64** [comment]
Or perhaps the meta-package Bio.jl (which could be kept as the Gitter) could remain the place for these issues.

**Comment by Ward9250** [comment]
I think we need a place other than the Gitter. Whilst I was travelling yesterday and today I began drafting a proposed code of conduct and incident response protocol - since as the user base and people participating in BioJulia increases, so may the likelihood of some people who do not conduct themselves professionally. One of the guidelines I found during my research of these kinds of things is to have a place to record when people come to maintainers and admins with a report of online abuse or harassment, but perhaps then such a place should be a private repos, as there may be things said in confidence.

**Comment by kescobo** [comment]
@Ward9250 I agree with you that we need something like this - something other than gitter. What I meant to say was that I'm not sure it needs to be separate from a code repo. 

Now that I think about it - we should see if we can follow whatever convention Base julia uses - do they have a community issues repo?
