### ISSUE TITLE
Neuro Imaging

### ISSUE THREAD

**Issue by prcastro** [BioJulia/Bio.jl#44]
Would be nice if Bio.jl offered a framework to Neuro Imaging (bio imaging in general). I do not have the expertise and don't know if this is the place for something like this. I couldn't find any package that offered such capabilities.

I was thinks of something on the lines of MATLAB's FieldTrip to deal with EEG or MEG analysis. Something for MRI would also be very nice.

Is this the right place?

**Comment by Blahah** [comment]
I think it's perfect for a Bio package, once we're ready for that. Perhaps we should start thinking about the  package system infrastructure.

**Comment by Ward9250** [comment]
I do know people in TSL who do image analysis - fluorescence microscopy and that sort of thing, and he's a good programmer too!

**Comment by Ward9250** [comment]
Also @Blahah perhaps this is one for the Gitter or message board, but once we have a core, how do you think we should schedule pulls and updates/releases and package manager subs? I worry that ad hoc might be a but unreliable, and doing things by feature may make it ad hoc because some features come faster than others, but then you don't want to say "this is a stability improvement only" update because contributors might just wait until features can be added again. I'd be a fan of the Linux way of doing it by time and merge windows. So every period of time, there's submissions and PRs and then at the end of the time period there's review and pulls. The con of that is at present we are small and so lapses might occur.

**Comment by dcjones** [comment]
@brk00 This maybe isn't what you're looking for but there is an [EEG.jl](https://github.com/codles/EEG.jl) that appears to have made significant progress. Also, Tim Holy's lab is focused on neural imaging, and he (with others) developed [Images.jl](https://github.com/timholy/Images.jl). It's not bio-specific per se, but presumably pretty suitable for biological imaging since that's Tim's major use case.

**Comment by brk00** [comment]
Maybe we should talk to @codles and check if he is interested in working with this kind of framework.

**Comment by codles** [comment]
Hey, thanks for adding me to the conversation. @dcjones is correct, I've tried to make EEG.jl like a fieldtrip for julia. Most of the code isn't EEG specific, and I guess would work with MEG. Maybe I should change the name. Imaging wise there currently isn't much, just the ability to read and process the output from [BESA](http://www.besa.de).

I appreciate you taking a look at the code Ive written. Ive tried to create general functions that could be used with any EEG analysis (resting state, evoked transient or evoked steady state). And then define a type that calls these general functions with specific defaults. Ive learnt a lot about coding in Julia since I started this project, so I'm currently going back through and fixing some of the rookie mistakes (when I have time) and adding more tests.
