### ISSUE TITLE
RFC: Bio package system

### ISSUE THREAD

**Issue by blahah** [BioJulia/Bio.jl#45]
As we approach release of the core, we should start planning the package system.

We have previously decided that all functionality apart from the core will be provided via a package system, and that the package system will have peer review and rules about code reuse, correctness and style to ensure high quality.

Let's use this issue to flesh out those ideas and decided on details that will be be important for implementation.

Note: following from discussion in #44.

**Comment by Ward9250** [comment]
I guess one of the first things is - Someone wants to contribute, if they come up with some functionality that would be benefit all Bio related operations and had many applications, core may be the better place for it, otherwise if it's very specific then a package is better. How do we help them decide? Perhaps we collect some examples of things in the past contributed as packages, and things that were better suited to being in core.

**Comment by dcjones** [comment]
There's not a really a straightforward way to have a parallel package system in julia now. I think that will become possible in the future though. One relevant issue: https://github.com/JuliaLang/METADATA.jl/issues/2417

I don't know that there will be a need in the meantime (it depends wether people write bio packages), but adopting things in the BioJulia organization and enforcing certain standards with regards to testing and documentation seems like a reasonable interim solution.

**Comment by Ward9250** [comment]
So when someone has a good release that has good testing and so on, the organization forks it/pulls on their fork?

**Comment by dcjones** [comment]
I was think more that they transfer ownership to BioJulia and they get added as maintainer.

**Comment by Ward9250** [comment]
That would be good too!
