### ISSUE TITLE
Importing functions from the Base module.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#96]
In Bio.jl, we often extend functions exported from the `Base` module. But as @dcjones said (https://github.com/BioJulia/Bio.jl/pull/85#discussion_r39339225), it is annoying to synchronize method definitions with the `import Base` statement.

I listed four possible styles for importing names to extend. pros and cons are my opinion, you may not agree.
The last style is a suggestion from my side.

### 1. always add `Base.` to definitions like `function Base.foo()`

* pros:
    * explicit
    * no need to keep synchronizing method definitions with the import statement
* cons:
    * verbose when defining methods

### 2. explicitly import methods from `Base` in every module (the current style)

* pros:
    * explicit
    * less verbose when defining methods
* cons:
    * need to keep synchronizing method definitions with the import statement

### 3. `importall Base` (suggested by @prcastro https://github.com/BioJulia/Bio.jl/pull/85#discussion_r39340739)

* pros:
    * less verbose when defining methods
* cons:
    * implicit
    * possible to accidentally extend methods

### 4. define an extendable method list shared across `Bio` modules

This is something like this:

```julia
macro bio_base_import()
    quote
        # these methods can be extended
        import Base:
            convert,
            length,
            ...
    end
end
```
, and call this macro in each modules:

```julia
module Bio.Seq

@bio_base_import

...
```

* pros:
    * explicit
    * less verbose when defining methods
* cons:
    * possible to accidentally extend methods as `importall Base` style, but somewhat less chance to do

**Comment by dcjones** [comment]
Thanks for opening this. I started out preferring to import everything at the beginning of the module (option 1), but my opinion has gradually changed as I wrote more julia code, and now I'd rather just qualify things with `Base.` (option 2).

The problem with explicit imports is that when extending a method, you have to switch to another file, look through a long list of names to see if it's already there, then add it to the list if it isn't. Then when reading code it's not immediately clear if a method is being extended. To know for sure, you have to again switch to another file and look through a list of names. If you forget to import the method, your code can fail in subtle ways when some unrelated code dispatches to the wrong function.

With `importall` (option 3), you no longer have the option of defining a function that has the same name as something in base, but doesn't extend the base method. It's rare that you might want to do that, but I think it does happen. We would also have to `importall` from multiple modules, because sometimes we are extending methods not from Base but from other packages.

Using a macro would be better than `importall`, but still has the problem of needing to cross-reference names to see if a method is being extended, and can still introduce errors when you forgot to add a name to the import list.

**Comment by Ward9250** [comment]
I would also like to propose an option 5 (building on option 4) which could also get my vote if it was added to the list:

# 5. Define several macros that import logical groups of base definitions.

This way, I know in Phylo - I'm going to be using start, next, done methods and iterators. So I would use a macro that imports them:
`@bio_base_iterators_import`

Then say I need to overwrite base logical operators for Phy Nodes and trees, well I better import that group:
`@bio_base_logical_import`

and so on.

I think this improves on 4, since for the cost of a few extra statements (but nowhere near as many as importing each thing explicitly) we would gain a lot of each in cross checking - because each macro tells you which of the base methods are being imported and extended. So when I get to - say - a `next` method and `@bio_base_logical_import` was used, well I know that `next()` is extening the base one.

**Comment by bicycle1885** [comment]
> The problem with explicit imports is that when extending a method, you have to switch to another file, look through a long list of names to see if it's already there, then add it to the list if it isn't. Then when reading code it's not immediately clear if a method is being extended. To know for sure, you have to again switch to another file and look through a list of names. If you forget to import the method, your code can fail in subtle ways when some unrelated code dispatches to the wrong function.

Now I completely agreed. The more I write Julia code, the stronger I believe always prefixing `Base.` to every function definition is a better way to extend an existing method. I couldn't remember all methods imported from other modules, and often accidentally forgot to import/export methods that I intended to extend. #98 and #108 are these examples.
